token:
  expiration_time: 86400000
  #secret: user_token_length_grater_128_over_required_therfore_meaningless_string_make-native_application
  #secret: user_token_length_grater_128_over_required_therfore_meaningless_string_make
  #secret: user_token_length_grater_128_over_required_therfore_meaningless_changed_#3
  secret: '{cipher}AQAHrZ53gdti02GovXIDmRpmS1CnvWanVlXP/bUyWHRor8sarFDwBnptKNccJFqkBgJcSw4VplnhY5nhNxs/lswD7tiFWNjMn37ffcYodu2HcATKX7r02EurvEPC0PgpTt1Jj1ENavsH0OkzvYS3jBdxtSEqGiwftBdRHZENHqZeRr6Gmwwrdf9WPLhEMhcIEZlar4PSGTpWOJZEw2E/2AemX+hA6Tj5DEFICSenzErgZg61DgZeN+xFlxmpTV+jyPvHew/+RxvAieUuoaQ58kIA8SBp896ta/9vmRjvrwFJl4SFjTV6NIBMNfAoZn1JK7Yba8g4VsrjU6juxH9QURg1x3OID1v0+mwodqKVDLo5gU1tt7UOoSgNt8kOGXF5I/nLB5hHFYrxmjk81JS95P9s4UaVVEpznoI1I9SBKrbrcfzMhU+Fc/7h3UiJP7NDzYf4U2IMSl/NzGw1O3CoAoya'

gateway:
  ip: 61.81.231.68

noojun:
  test: abcdefghijklmnopqrstuvwxyz!@#!@#
